name: Docker Image CI
on:
  push:
    branches: [ main ]
env:
  GHCR_REPO: akiranohikari/pysauce
  DOCKER_REPO: akiranohikari/pysauce
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2 
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Login to Github Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/arm64
        push: true
        pull: true
        cache-from: type=gha, scope=${{ github.workflow }}
        cache-to: type=gha, scope=${{ github.workflow }}
        tags: |
          docker.io/${{ env.DOCKER_REPO }}:latest
          ghcr.io/${{ env.GHCR_REPO }}:latest
